package com.pfm.serviceimpl;

import java.time.LocalDate;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.pfm.entity.Transaction;
import com.pfm.entity.TxnType;
import com.pfm.entity.User;
import com.pfm.repo.ReportRepo;
import com.pfm.repo.UserRepo;
import com.pfm.service.ReportService;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.security.Principal;
import java.util.stream.Stream;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;

@Service
public class ReportServiceImpl implements ReportService {

	@Autowired
	private ReportRepo reportRepo;

	@Autowired
	private UserRepo userRepo;

	@Override
	public List<Transaction> getFilteredTransactions(User user, LocalDate from, LocalDate to, String type) {

		if (type == null || type.isEmpty())
			type = "EXPENSE";

		if (type.equalsIgnoreCase("BOTH"))
			return reportRepo.findByUserAndDateBetween(user, from, to);

		TxnType txnType = TxnType.valueOf(type.toUpperCase());
		return reportRepo.findByUserAndDateBetweenAndType(user, from, to, txnType);
	}

	@Override
	public List<Transaction> fetchFilteredTransactions(String fromDate, String toDate, String type,
			Principal principal) {

		User user = userRepo.findByEmail(principal.getName()).orElseThrow(() -> new RuntimeException("User not found"));
		LocalDate from = LocalDate.parse(fromDate);
		LocalDate to = LocalDate.parse(toDate);

		return getFilteredTransactions(user, from, to, type);
	}

	@Override
	public byte[] generatePdf(List<Transaction> transactions) {

		try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {

			Document document = new Document(PageSize.A4, 40, 40, 40, 40);
			PdfWriter.getInstance(document, out);
			document.open();

			// Title
			Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, new Color(30, 41, 59));
			Paragraph title = new Paragraph("Transactions Report", titleFont);
			title.setAlignment(Element.ALIGN_CENTER);
			title.setSpacingAfter(10f);
			document.add(title);

			// Subtitle with date range
			Font subtitleFont = FontFactory.getFont(FontFactory.HELVETICA, 12, new Color(100, 116, 139));
			Paragraph subtitle = new Paragraph("Generated on: " + LocalDate.now(), subtitleFont);
			subtitle.setAlignment(Element.ALIGN_CENTER);
			subtitle.setSpacingAfter(15f);
			document.add(subtitle);

			// Table
			PdfPTable table = new PdfPTable(5);
			table.setWidthPercentage(100);
			table.setSpacingBefore(10f);
			float[] columnWidths = { 2f, 3f, 2f, 1.5f, 2f };
			table.setWidths(columnWidths);

			// Header
			Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Color.WHITE);
			Stream.of("Date", "Description", "Category", "Type", "Amount").forEach(col -> {
				PdfPCell cell = new PdfPCell(new Phrase(col, headerFont));
				cell.setBackgroundColor(new Color(30, 58, 138));
				cell.setHorizontalAlignment(Element.ALIGN_CENTER);
				cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
				cell.setPadding(12f);
				cell.setBorderWidth(1f);
				cell.setBorderColor(new Color(226, 232, 240));
				table.addCell(cell);
			});

			// Data rows with alternating colors
			Font dataFont = FontFactory.getFont(FontFactory.HELVETICA, 10, new Color(71, 85, 105));
			boolean isEvenRow = false;
			for (Transaction txn : transactions) {
				Color rowColor = isEvenRow ? new Color(248, 250, 252) : Color.WHITE;

				addStyledCell(table, txn.getDate().toString(), dataFont, rowColor);
				addStyledCell(table, txn.getDescription(), dataFont, rowColor);
				addStyledCell(table, txn.getCategory().getName(), dataFont, rowColor);
				addStyledCell(table, txn.getType().name(), dataFont, rowColor);
				addStyledCell(table, "₹" + String.valueOf(txn.getAmount()), dataFont, rowColor);

				isEvenRow = !isEvenRow;
			}

			document.add(table);

			// Footer
			Paragraph footer = new Paragraph("\n\nReport generated by Personal Finance Manager",
					FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 10, new Color(100, 116, 139)));
			footer.setAlignment(Element.ALIGN_CENTER);
			document.add(footer);

			document.close();

			return out.toByteArray();

		} catch (Exception e) {
			throw new RuntimeException("PDF generation failed", e);
		}
	}

	private void addStyledCell(PdfPTable table, String content, Font font, Color bgColor) {
		PdfPCell cell = new PdfPCell(new Phrase(content, font));
		cell.setBackgroundColor(bgColor);
		cell.setHorizontalAlignment(Element.ALIGN_CENTER);
		cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
		cell.setPadding(10f);
		cell.setBorderWidth(1f);
		cell.setBorderColor(new Color(226, 232, 240));
		table.addCell(cell);
	}

}
